name: clinical-curator
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip

  # Deep learning
  - pytorch>=2.1
  - torchvision>=0.16
  - torchaudio>=2.1
  - pytorch-cuda=12.1      # remove this line if CPU-only

  # Scientific computing
  - numpy>=1.24
  - pandas>=2.0
  - scipy>=1.11
  - scikit-learn>=1.3
  - pillow>=10.0
  - opencv>=4.8

  # Visualisation
  - matplotlib>=3.7
  - seaborn>=0.13

  # API backend
  - pip:
    - fastapi>=0.110
    - uvicorn[standard]>=0.27
    - python-multipart>=0.0.9
    - fpdf2>=2.7
    - kagglehub>=0.2
    - optuna>=3.5
    - tqdm>=4.66
